[package]
name = "data-generator"
version = "0.1.0"
authors = ["amedvedev <amedvyedyev@gmail.com>"]

[lib]
name = "data_generator"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
clap = "2.31.2"
serde = "1.0"
serde_json = "1.0.17"
chrono = "0.4"